// Generated by https://quicktype.io

import { GetProductModel } from '../product/product.model';
import { APIResponseModel, PaginatedData } from '../shared-model.model';

export interface CreateOrderModel {
  customerEmail: string;
  shippingAddress: ShippingAddress;
  orderItems: OrderItem[];
}

export interface OrderItem {
  productId: number;
  quantity: number;
  product: GetProductModel;
}

export interface ShippingAddress {
  street: string;
  city: string;
  state: string;
  country: string;
  zipCode?: string;
  email?: string;
}
// Generated by https://quicktype.io

export interface GetOrderModel {
  customerEmail: string;
  shippingAddress: ShippingAddress;
  orderItems: OrderItem[];
  id: number;
  createdAt: string;
  totalItem: number;
  totalAmount: number;
}

export interface OrderPagedList extends PaginatedData<GetOrderModel> {}

export interface GetOrderListResponse
  extends APIResponseModel<OrderPagedList> {}
